spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/we_chat?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 12306
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml